import type { Metadata } from "next";
import { HeaderNavigation } from "@/components/common/header";
import Footer from "@/components/common/footer";

export const metadata: Metadata = {
    title: "oShool - Study online",
    description: "Generated by create next app",
};

export default function Layout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <>
            <HeaderNavigation />
            {children}
            <Footer />
        </>

    );
}
